export const colors = [
  { label: "Warm Red", value: "#EF5350" },
  { label: "Fresh Green", value: "#81C784" },
  { label: "Sky Blue", value: "#4FC3F7" },
  { label: "Goldenrod", value: "#FDD835" },
  { label: "Charcoal", value: "#424242" },
  { label: "Eggshell", value: "#FAF9F6" },
  { label: "Cool Aqua", value: "#4DB6AC" },
  { label: "Lilac", value: "#B39DDB" },
  { label: "Silver", value: "#BDBDBD" },
  { label: "Medium Gray", value: "#757575" },
  { label: "Brick", value: "#A05252" },
  { label: "Olive Green", value: "#9E9D24" },
  { label: "Soft Purple", value: "#9575CD" },
  { label: "Medium Teal", value: "#26A69A" },
  { label: "Slate", value: "#5C6BC0" },
];
