import { DemoData } from "@/demo-context";

export const initialDemoData: DemoData = {
  user: {
    _id: "demo-user-1",
    username: "Demo User",
    password: "demo-password",
    email: "demo@example.com",
    firstName: "Alex",
    lastName: "Smith",
    occupation: "Software Engineer",
    profileImagePath: null,
  },
  investments: [
    {
      _id: "demo-investment-id",
      userId: "demo-user-1",
      brokerageName: "Vanguard",
      type: "Stocks",
      subtype: "ETF",
      color: "#EF5350",
      statements: [
        {
          _id: "demo-statement-id-1",
          startDate: new Date(2025, 1, 1),
          startBalance: 3324.72,
          endDate: new Date(2025, 1, 28),
          endBalance: 3261.94,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-2",
          startDate: new Date(2025, 2, 1),
          startBalance: 3261.94,
          endDate: new Date(2025, 2, 31),
          endBalance: 3071.49,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-3",
          startDate: new Date(2025, 3, 1),
          startBalance: 3071.49,
          endDate: new Date(2025, 3, 30),
          endBalance: 3048.92,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
      ],
    },
    {
      _id: "demo-investment-id-2",
      userId: "demo-user-1",
      brokerageName: "Fidelity",
      type: "Stocks",
      subtype: "Individual",
      color: "#81C784",
      statements: [
        {
          _id: "demo-statement-id-4",
          startDate: new Date(2025, 0, 1),
          startBalance: 2855.25,
          endDate: new Date(2025, 0, 31),
          endBalance: 2855.25,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-5",
          startDate: new Date(2025, 1, 1),
          startBalance: 2855.25,
          endDate: new Date(2025, 1, 28),
          endBalance: 2855.25,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-6",
          startDate: new Date(2025, 2, 1),
          startBalance: 2855.25,
          endDate: new Date(2025, 2, 31),
          endBalance: 2725.59,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-7",
          startDate: new Date(2025, 3, 1),
          startBalance: 2725.59,
          endDate: new Date(2025, 3, 30),
          endBalance: 2725.59,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
      ],
    },
    {
      _id: "demo-investment-id-3",
      userId: "demo-user-1",
      brokerageName: "Webull",
      type: "Stocks",
      subtype: "Individual",
      color: "#4FC3F7",
      statements: [
        {
          _id: "demo-statement-id-8",
          startDate: new Date(2024, 11, 31),
          startBalance: 8559.66,
          endDate: new Date(2025, 0, 31),
          endBalance: 8626.71,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-9",
          startDate: new Date(2025, 0, 31),
          startBalance: 8647.57,
          endDate: new Date(2025, 1, 28),
          endBalance: 8354.4,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-10",
          startDate: new Date(2025, 1, 28),
          startBalance: 8376.58,
          endDate: new Date(2025, 2, 31),
          endBalance: 7597.77,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
        {
          _id: "demo-statement-id-11",
          startDate: new Date(2025, 2, 31),
          startBalance: 7597.77,
          endDate: new Date(2025, 3, 30),
          endBalance: 7652.45,
          depositAmount: 0,
          withdrawalAmount: 0,
        },
      ],
    },
  ],
};
